In [35]:
# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [36]:
#loading the dataset
df=pd.read_csv('emails.csv')

In [37]:
#checking dataset 
df

,Email No.,the,to,ect,and,for,of,a,you,hou,...,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry,Prediction
0,Email 1,0,0,1,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Email 2,8,13,24,6,6,2,102,1,27,...,0,0,0,0,0,0,0,1,0,0
2,Email 3,0,0,1,0,0,0,8,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Email 4,0,5,22,0,5,1,51,2,10,...,0,0,0,0,0,0,0,0,0,0
4,Email 5,7,6,17,1,5,2,57,0,9,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5167,Email 5168,2,2,2,3,0,0,32,0,0,...,0,0,0,0,0,0,0,0,0,0
5168,Email 5169,35,27,11,2,6,5,151,4,3,...,0,0,0,0,0,0,0,1,0,0
5169,Email 5170,0,0,1,1,0,0,11,0,0,...,0,0,0,0,0,0,0,0,0,1
5170,Email 5171,2,7,1,0,2,1,28,2,0,...,0,0,0,0,0,0,0,1,0,1
5171,Email 5172,22,24,5,1,6,5,148,8,2,...,0,0,0,0,0,0,0,0,0,0

In [38]:
df.columns

Index(['Email No.', 'the', 'to', 'ect', 'and', 'for', 'of', 'a', 'you', 'hou',
       ...
       'connevey', 'jay', 'valued', 'lay', 'infrastructure', 'military',
       'allowing', 'ff', 'dry', 'Prediction'],
      dtype='object', length=3002)

In [39]:
len(df.columns)

3002

In [40]:
len(df)

5172

In [41]:
df.info

<bound method DataFrame.info of        Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  \
0        Email 1    0   0    1    0    0   0    2    0    0  ...         0
1        Email 2    8  13   24    6    6   2  102    1   27  ...         0
2        Email 3    0   0    1    0    0   0    8    0    0  ...         0
3        Email 4    0   5   22    0    5   1   51    2   10  ...         0
4        Email 5    7   6   17    1    5   2   57    0    9  ...         0
...          ...  ...  ..  ...  ...  ...  ..  ...  ...  ...  ...       ...
5167  Email 5168    2   2    2    3    0   0   32    0    0  ...         0
5168  Email 5169   35  27   11    2    6   5  151    4    3  ...         0
5169  Email 5170    0   0    1    1    0   0   11    0    0  ...         0
5170  Email 5171    2   7    1    0    2   1   28    2    0  ...         0
5171  Email 5172   22  24    5    1    6   5  148    8    2  ...         0

      jay  valued  lay  infrastructure  military  allowing  ff  dry  \
0       0       0    0               0         0         0   0    0
1       0       0    0               0         0         0   1    0
2       0       0    0               0         0         0   0    0
3       0       0    0               0         0         0   0    0
4       0       0    0               0         0         0   1    0
...   ...     ...  ...             ...       ...       ...  ..  ...
5167    0       0    0               0         0         0   0    0
5168    0       0    0               0         0         0   1    0
5169    0       0    0               0         0         0   0    0
5170    0       0    0               0         0         0   1    0
5171    0       0    0               0         0         0   0    0

      Prediction
0              0
1              0
2              0
3              0
4              0
...          ...
5167           0
5168           0
5169           1
5170           1
5171           0

[5172 rows x 3002 columns]>

In [42]:
# here we undersstand that dataset has 3472 rows and 3002 columns 
# Now we check if any Null value is present or not 
df.isnull().sum()

Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3002, dtype: int64

In [43]:
# we max fucntion to find null values
df.isnull().sum().max()

0

In [44]:
# # since maximum value is 0 and 1 value is not present
# so we do not have any null values in this dataset

In [45]:
df

,Email No.,the,to,ect,and,for,of,a,you,hou,...,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry,Prediction
0,Email 1,0,0,1,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Email 2,8,13,24,6,6,2,102,1,27,...,0,0,0,0,0,0,0,1,0,0
2,Email 3,0,0,1,0,0,0,8,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Email 4,0,5,22,0,5,1,51,2,10,...,0,0,0,0,0,0,0,0,0,0
4,Email 5,7,6,17,1,5,2,57,0,9,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5167,Email 5168,2,2,2,3,0,0,32,0,0,...,0,0,0,0,0,0,0,0,0,0
5168,Email 5169,35,27,11,2,6,5,151,4,3,...,0,0,0,0,0,0,0,1,0,0
5169,Email 5170,0,0,1,1,0,0,11,0,0,...,0,0,0,0,0,0,0,0,0,1
5170,Email 5171,2,7,1,0,2,1,28,2,0,...,0,0,0,0,0,0,0,1,0,1
5171,Email 5172,22,24,5,1,6,5,148,8,2,...,0,0,0,0,0,0,0,0,0,0

In [46]:
#drop the Email.No column as it serves no purpose in this dataset
# we remove Email no column from the dataset so we give df.columns[1:] and we create 2 variables 
# for x we take all rows and all columns except the last one, so [:-1]
# for y we take only the last column so [-1]
# create input data as x input
x = df[df.columns[1:-1]]
# create input data as y input
y = df[df.columns[-1]]

In [47]:
x.head(5)

,the,to,ect,and,for,of,a,you,hou,in,...,enhancements,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry
0,0,0,1,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,8,13,24,6,6,2,102,1,27,18,...,0,0,0,0,0,0,0,0,1,0
2,0,0,1,0,0,0,8,0,0,4,...,0,0,0,0,0,0,0,0,0,0
3,0,5,22,0,5,1,51,2,10,1,...,0,0,0,0,0,0,0,0,0,0
4,7,6,17,1,5,2,57,0,9,3,...,0,0,0,0,0,0,0,0,1,0

In [48]:
y.head(5)

0    0
1    0
2    0
3    0
4    0
Name: Prediction, dtype: int64

In [49]:
# we have our x and y variable ready.
# now we import new libraries to encode the Email column
from sklearn import preprocessing
from sklearn import tree
from sklearn.model_selection import train_test_split

In [50]:
# now we create training and testing data for our model
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=69)

In [51]:
# now we check our testing and training variables
x_train.head(5)

,the,to,ect,and,for,of,a,you,hou,in,...,enhancements,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry
4591,5,3,1,2,1,0,32,4,0,9,...,0,0,0,0,0,0,0,0,0,0
4537,20,7,1,6,9,7,94,1,3,16,...,0,0,0,0,0,0,0,0,1,0
747,8,6,9,4,3,0,58,1,5,5,...,0,0,0,0,0,0,0,0,0,0
4639,1,1,1,0,1,0,10,0,1,1,...,0,0,0,0,0,0,0,0,0,0
3397,5,2,2,3,2,1,40,6,0,10,...,0,0,0,0,0,0,0,0,0,0

In [52]:
x_test.head(5)

,the,to,ect,and,for,of,a,you,hou,in,...,enhancements,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry
3514,5,2,2,3,2,1,40,5,1,10,...,0,0,0,0,0,0,0,0,0,0
3725,38,32,8,17,26,29,276,0,7,100,...,0,0,0,1,0,0,0,0,2,0
442,5,5,1,0,2,2,25,1,0,5,...,0,0,0,0,0,0,0,0,1,0
1316,2,4,3,3,4,1,107,3,0,22,...,0,0,0,0,0,0,0,0,1,0
5086,1,2,1,3,0,0,20,2,0,1,...,0,0,0,0,0,0,0,0,0,0

In [53]:
y_train.head(5)

4591    0
4537    0
747     0
4639    0
3397    1
Name: Prediction, dtype: int64

In [54]:
y_test.head(5)

3514    1
3725    1
442     0
1316    1
5086    1
Name: Prediction, dtype: int64

In [55]:
#now we import decision tree classfier
from sklearn.tree import DecisionTreeClassifier

In [56]:
# Creating new model
model_kiran = DecisionTreeClassifier()

In [57]:
model_kiran

DecisionTreeClassifier()

In [58]:
# Our training and testing x, y variables are ready.
# now we fit them in a model
model_kiran.fit(x_train,y_train)

DecisionTreeClassifier()

In [59]:
# now the training data is fed to our model
# Now testing new Model prediction by providing Test Data set
y_kiran=model_kiran.predict(x_test)

In [60]:
# this is our variable which has learned the test data
y_kiran

array([1, 1, 0, ..., 0, 1, 0], dtype=int64)

In [61]:
# to check accuracy we need to import another library
from sklearn.metrics import accuracy_score, classification_report

In [62]:
# Compare predictions with testing data given
# this will only give accuracy
accuracy = accuracy_score(y_test, y_kiran)
print(accuracy)

0.9333333333333333

In [63]:
# Generate a detailed classification report
report = classification_report(y_test, y_kiran)
print(report)

              precision    recall  f1-score   support

           0       0.95      0.96      0.95       717
           1       0.91      0.87      0.89       318

    accuracy                           0.93      1035
   macro avg       0.93      0.92      0.92      1035
weighted avg       0.93      0.93      0.93      1035

In [64]:
#  so finally we get an accuracy of 92% when we keep test_size as 80/20
# if we change this to 70/30 then
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=69)
model_kiran.fit(x_train,y_train)
y_kiran=model_kiran.predict(x_test)
accuracy = accuracy_score(y_test, y_kiran)
print(accuracy)
report = classification_report(y_test, y_kiran)
print(report)

0.9304123711340206
              precision    recall  f1-score   support

           0       0.94      0.96      0.95      1083
           1       0.90      0.87      0.88       469

    accuracy                           0.93      1552
   macro avg       0.92      0.91      0.92      1552
weighted avg       0.93      0.93      0.93      1552

In [65]:
# here we see that 70/30 splitting gives more better accuracy of 93%.
# thus we conclude that 70/30 split gives better accuracy for this dataset.